# Setup

Need to have the following
* Python 3
* SciPy, NumPy, SymPy, Matplotlib
* Jupyter notebook

Recommended to install Anaconda3 which also comes with many useful scientific packages.

# Python (3) tutorial

Based on the official [Python tutorial](https://docs.python.org/3/tutorial/introduction.html)

### Python version

We are going to use Python 3. If you are using Python 2, please switch to Python 3 for this class.

In [121]:
# Checking your python version
import sys # importing sys package
print(sys.version)
print(type(sys.version))

3.6.5 |Anaconda custom (64-bit)| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
<class 'str'>


## Basic data types

### Numbers

In [124]:
x = -2
print(x, type(x))

-2 <class 'int'>


In [125]:
print(x + 1)   # Addition;
print(x - 1)   # Subtraction;
print(x * 2)   # Multiplication;
print(x ** 7)  # Exponentiation;

-1
-3
-4
-128


```
i++
i--
++i
--i
```
are not available.

In [126]:
x += 1 # x = x + 1
print(x)  # Prints "4"
x *= 2 # x = x * 2
print(x) # Prints "8"

-1
-2


In [127]:
y = 2.5
print(type(y)) # Prints "<type 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'float'>
2.5 3.5 5.0 6.25


In [128]:
8 / 5  # division always returns a floating point number

1.6

In [129]:
17 // 3  # floor division discards the fractional part

5

In [131]:
17 % 4

1

In [134]:
17 / 3  # classic division returns a float

5.666666666666667

### Booleans

Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc.):

In [150]:
# True or False, 0 and not 0, None, '', -1, 2, 3, 
is_spam = None

In [147]:
if is_spam:
    print('Spam')
else:
    print('Not Spam')

Not Spam


### Strings

In [151]:
s = 'spam eggs'  # both string and character literals can use single quotes
print(s, type(s), len(s))

spam eggs <class 'str'> 9


In [152]:
'doesn\'t'  # use \' to escape the single quote...

"doesn't"

In [153]:
print(type('doesn\'t'))

<class 'str'>


In [ ]:
"doesn't"  # ...or use double quotes instead

In [154]:
print(type("doesn't"))

<class 'str'>


In [155]:
s = "hello. apple jack"
print(s.capitalize())           # Capitalize a string; prints "Hello"
print(s.upper())                # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))               # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))              # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())       # Strip leading and trailing whitespace; prints "world"



Hello. apple jack
HELLO. APPLE JACK
hello. apple jack
hello. apple jack
he(ell)(ell)o. app(ell)e jack
world


In [ ]:
line = '    3, 5, 5.6, 7, 8\n'

In [161]:
l = line.strip()
l

'3, 5, 5.6, 7, 8'

In [165]:
la = l.split(',')
print(la, type(la))

['3', ' 5', ' 5.6', ' 7', ' 8'] <class 'list'>


In [166]:
lclean = []
for e in la:
    lclean.append(e.strip())

print(lclean)

['3', '5', '5.6', '7', '8']


In [168]:
lclean = [ e.strip() for e in la ]

In [167]:
ls = [ float(l) for l in lclean ]

In [171]:
ls = [float(l.strip(', ')) for l in line.strip().split()]

In [172]:
print(ls)

[3.0, 5.0, 5.6, 7.0, 8.0]


### String formatting

In [174]:
x = 5.88567
print(x)

5.88567


In [175]:
s = f'The value of x= {x:.2f}'
print(s, type(s))

The value of x= 5.89 <class 'str'>


In [179]:
a = 34
b = 678
h = 98
s = f'a = {a}, h: {h}, b: {b:5d}, '
print(s)

a = 34, h: 98, b:   678, 


In [181]:
f'{42*-1:+d}'

'-42'

In [ ]:
# print first 100 natural numbers
for i in range(1, 101):
    print(f'{i:3d}')

In [182]:
word = 'Python'

# indexing & slicing

```
 +---+---+---+---+---+---+
 | P | y | t | h | o | n |
 +---+---+---+---+---+---+
 0   1   2   3   4   5   6
-6  -5  -4  -3  -2  -1
```

In [183]:
word[0]  # character in position 0

'P'

In [184]:
word[-2]  # second-last character

'o'

In [185]:
word[-1]

'n'

In [186]:
word[0:2]  # characters from position 0 (included) to 2 (excluded)

'Py'

In [187]:
word[2:5]  # characters from position 2 (included) to 5 (excluded)

'tho'

In [188]:
word[0] = 'J'

TypeError: 'str' object does not support item assignment

### strings are immutable in python

In [189]:
# python strings are immutable
word = 'Python'
word = 'J' + word[1:]
print(word)

Jython


## Containers

### Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [190]:
a = [0, 1, 2, 3, 4]
print(a)

[0, 1, 2, 3, 4]


In [ ]:
print(a[-1]) # 

In [191]:
a[1:-1]

[1, 2, 3]

In [ ]:
a[::-1]

In [192]:
print(type(a))

<class 'list'>


In [193]:
a[0] = 'J'

In [194]:
a

['J', 1, 2, 3, 4]

In [195]:
a[1] = [1, 2, 3, 4]
a

['J', [1, 2, 3, 4], 2, 3, 4]

In [197]:
a = ['a', 'a', 1, 2, 3, 1, 2, 3]

In [198]:
s = set(a)

In [199]:
print(s)

{1, 2, 3, 'a'}


In [201]:
for e in s:
    print(e)

1
2
3
a


In [207]:
d = {1: 3, 3: -10, -40: 50}

In [208]:
print(d)

{1: 3, 3: -10, -40: 50}


In [204]:
print(type(d))

<class 'dict'>


In [211]:
for key in d:
    print(f'{key} -> {d[key]}')

1 -> 3
3 -> -10
-40 -> 50


## Loops

You can loop over the elements of a list like this:

In [196]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


If you want access to the index of each element within the body of a loop, use the built-in enumerate function:

In [212]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print(f'#{idx+1}: {animal}')

#1: cat
#2: dog
#3: monkey


# Loops exercise

Print the first $n$ fibonacci numbers.

$$ a_1 = 1,  a_2 = 1, a_3 = 2, a_4 = 3, \dots$$

where $a_n = a_{n-1} + a_{n-2}$

In [4]:
a, b = 1, 1
i = 1
while i <= 10:
    # single line comments
    '''
    multi-line
    comments
    '''
    print(a, end=', ')
    a, b = b, a+b
    i += 1

1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 

In [5]:
a, b = 1, 1
for i in range(10):
    print(a, end=', ')
    a, b = b, a+b

1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 

#### List  Comprehensions

In [215]:
# create a list of first 10 cubes
cubes = []

for i in range(1, 11):
    cubes.append(i**3)

print(cubes)

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


In [216]:
# cubes via list comprehension
cubes = [i**3 for i in range(1, 11)]
print(cubes)

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


In [ ]:
cubes.append(7**3) # add the cube of 7
print(cubes)

In [ ]:
# Swapping two variables
a = 5
b = 6
print(a, b)

In [ ]:
tmp = a
a = b
b = tmp
print(a, b)

In [ ]:
a, b = b, a
print(a, b)

In [217]:
a, b, c = 1, 2, 3
print(a, b, c)

1 2 3


## Dictionaries

A dictionary stores (key, value) pairs, similar to a Map in Java or an object in Javascript. You can use it like this

In [218]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d )    # Check if a dictionary has a given key; prints "True"

cute
True


In [219]:
d['fish'] = 'wet'    # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"

wet


In [221]:
d

{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}

In [220]:
print(d['monkey'])

KeyError: 'monkey'

In [222]:
del d['fish']

In [223]:
print(d)

{'cat': 'cute', 'dog': 'furry'}


It is easy to iterate over the keys in a dictionary:

In [224]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))


A person has 2 legs
A cat has 4 legs
A spider has 8 legs


If you want access to keys and their corresponding values, use the iteritems method:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))

Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

# exercise
Create a matrix A such that 

$$A_{i,j} = i*j $$

In [225]:
m, n = 5, 10

In [227]:
A = [  [i*j for j in range(1, n+1)] for i in range(1, m+1) ]
print(A)

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [2, 4, 6, 8, 10, 12, 14, 16, 18, 20], [3, 6, 9, 12, 15, 18, 21, 24, 27, 30], [4, 8, 12, 16, 20, 24, 28, 32, 36, 40], [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]]


In [228]:
import pprint

In [229]:
pprint.pprint(A)

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
 [3, 6, 9, 12, 15, 18, 21, 24, 27, 30],
 [4, 8, 12, 16, 20, 24, 28, 32, 36, 40],
 [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]]


In [230]:
# even prettier printing
from IPython.display import display
import sympy


def display_matrix(m):
    sympy.init_printing()
    display(sympy.Matrix(m))

In [231]:
display_matrix(A)

⎡1  2   3   4   5   6   7   8   9   10⎤
⎢                                     ⎥
⎢2  4   6   8   10  12  14  16  18  20⎥
⎢                                     ⎥
⎢3  6   9   12  15  18  21  24  27  30⎥
⎢                                     ⎥
⎢4  8   12  16  20  24  28  32  36  40⎥
⎢                                     ⎥
⎣5  10  15  20  25  30  35  40  45  50⎦

In [232]:
# some issues
A[1] # is second row

In [ ]:
# how to get first column ??

# NumPy

In [233]:
import numpy as np

In [234]:
a = list(range(1, 10))
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [235]:
print(type(a))

<class 'list'>


In [236]:
arr = np.array(a)

In [237]:
print(a)
print(arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


In [238]:
type(arr)

numpy.ndarray

In [239]:
print(arr.shape)

(9,)


In [240]:
A = np.zeros(5)
display_matrix(A)
print(A)
print(A.shape)

⎡0.0⎤
⎢   ⎥
⎢0.0⎥
⎢   ⎥
⎢0.0⎥
⎢   ⎥
⎢0.0⎥
⎢   ⎥
⎣0.0⎦

[0. 0. 0. 0. 0.]
(5,)


In [242]:
A = np.zeros((10, 10))
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [243]:
# identity matrix
Id = np.eye(10)

In [244]:
print(Id)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [247]:
Id[:, [1, 4, 6]]

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])